---
- hosts: web
  name: sample yaml
  become: yes
  vars:
    install_modules:
      - httpd
  tasks:
    - name: install module
      yum:
        name: "{{install_modules}}"
        state: present
